#!/usr/bin/env python3
# Build-time glyph atlas for strip's RENDER text path.
# Rasterizes a font to A8 coverage bitmaps and emits a NASM include
# (strip_glyphs.inc): a metric table + a 4-byte-scanline-padded alpha blob,
# matching glass's AddGlyphs convention (GLYPHINFO x=-bearingL, y=+bearingT).
#
# Re-run after changing FONT/SIZE:  python3 gen_strip_glyphs.py
import sys
from PIL import ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
SIZE = 13                      # px; advance ~8 (matches original Terminus width), ~12px tall

# ASCII + Latin-1 Supplement (·°±×÷ accents) + status-bar symbols seen on the
# real bar / used by striprc segments (markers, arrows, triangles, check marks,
# dashes, ellipsis, math). Cmap-filtered below so unsupported glyphs are
# dropped rather than rendered as .notdef boxes.
SYMBOLS = [
    0x2013, 0x2014,                     # – —
    0x2018, 0x2019, 0x201C, 0x201D,     # ‘ ’ “ ”
    0x2022, 0x2026,                     # • …
    0x2190, 0x2191, 0x2192, 0x2193, 0x2194,   # ← ↑ → ↓ ↔
    0x2248, 0x2260, 0x2264, 0x2265,     # ≈ ≠ ≤ ≥
    0x25A0, 0x25A1, 0x25AA, 0x25AB,     # ■ □ ▪ ▫
    0x25B2, 0x25BC, 0x25B6, 0x25C0,     # ▲ ▼ ▶ ◀
    0x25B8, 0x25C2, 0x25C6, 0x25C7,     # ▸ ◂ ◆ ◇
    0x25CB, 0x25CF, 0x25C9,             # ○ ● ◉
    0x2605, 0x2606,                     # ★ ☆
    0x2713, 0x2714, 0x2717, 0x2718,     # ✓ ✔ ✗ ✘
]
_cand = sorted(set(range(32, 127)) | set(range(160, 256)) | set(SYMBOLS))

try:
    from fontTools.ttLib import TTFont
    _cmap = TTFont(FONT).getBestCmap()
    CODEPOINTS = [c for c in _cand if c in _cmap]
except Exception:
    CODEPOINTS = _cand

font = ImageFont.truetype(FONT, SIZE)
ascent, descent = font.getmetrics()

entries = []   # (cp, w, h, x, y, adv, data_off)
blob = bytearray()

for cp in CODEPOINTS:
    ch = chr(cp)
    adv = round(font.getlength(ch))
    mask, (ox, oy) = font.getmask2(ch, mode="L")
    w, h = mask.size
    if w == 0 or h == 0:                 # space / empty glyph
        entries.append((cp, 0, 0, 0, 0, adv, len(blob)))
        continue
    raw = bytes(mask)                    # row-major, stride = w (mode L)
    stride = (w + 3) & ~3                # AddGlyphs pads scanlines to 4 bytes
    off = len(blob)
    for row in range(h):
        line = raw[row * w:(row + 1) * w]
        blob += line + b"\x00" * (stride - w)
    bearing_x = ox                       # left side bearing
    bearing_y = ascent - oy              # top bearing (baseline-up to bitmap top)
    x = (-bearing_x) & 0xFFFF            # GLYPHINFO x = -bearingL (s16)
    y = bearing_y & 0xFFFF               # GLYPHINFO y = +bearingT (s16)
    entries.append((cp, w, h, x, y, adv, off))

# Worst-case single-glyph AddGlyphs payload (28 header + padded alpha).
max_payload = 0
for (cp, w, h, x, y, adv, off) in entries:
    stride = (w + 3) & ~3
    max_payload = max(max_payload, 28 + stride * h)

out = []
out.append("; AUTO-GENERATED by gen_strip_glyphs.py — do not edit by hand.")
out.append(f"; font={FONT} size={SIZE} ascent={ascent} descent={descent}")
adv_mode = max(set(e[5] for e in entries), key=lambda a: sum(1 for e in entries if e[5] == a))
out.append(f"%define GLYPH_COUNT {len(entries)}")
out.append(f"%define GLYPH_ADVANCE {adv_mode}")
out.append(f"%define GLYPH_ADDREQ_MAX {(max_payload + 3) & ~3}")
out.append("; entry = cp(u32) w(u16) h(u16) x(s16) y(s16) adv(u16) pad(u16) off(u32) = 20 bytes")
out.append("glyph_table:")
for (cp, w, h, x, y, adv, off) in entries:
    out.append(f"    dd {cp}\n    dw {w}, {h}, {x}, {y}, {adv}, 0\n    dd {off}")
out.append(f"glyph_atlas_len equ {len(blob)}")
out.append("glyph_atlas:")
for i in range(0, len(blob), 32):
    out.append("    db " + ",".join(str(b) for b in blob[i:i+32]))
out.append("")

with open("strip_glyphs.inc", "w") as f:
    f.write("\n".join(out))

print(f"glyphs={len(entries)} ascent={ascent} descent={descent} "
      f"atlas={len(blob)}B max_addreq={(max_payload+3)&~3}B")
# Sample a few metrics to sanity-check.
for cp in (ord(' '), ord('A'), ord('g'), ord('0'), ord('.')):
    e = next(e for e in entries if e[0] == cp)
    print(f"  '{chr(cp)}' w={e[1]} h={e[2]} x={e[3] if e[3]<32768 else e[3]-65536} "
          f"y={e[4] if e[4]<32768 else e[4]-65536} adv={e[5]}")
